### PR TITLE
Fixed display of dynamicVariables menu when menuType is none

### LINKED ISSUE #1659: Display DynamicVariables menu when menuType is none
Ref: https://github.com/neetozone/neeto-molecules/issues/2674

### PR DESCRIPTION
**Pull request by SumitPanda0**
- Fixes #1659 

**Description**

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have updated the types definition of modified exports.
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by SumitPanda0** [comment]
@labeebklatif _a Please review this PR.

**Review by labeebklatif — APPROVED** [review]
@SumitPanda0 _a Added minor suggestion. You may merge this after update.

File: src/components/Editor/index.jsx [hunk 1]
```diff
@@ -265,30 +266,37 @@ const Editor = (
...
+              isIndependant={isMenuIndependent}
+              setIsNeetoKbArticleActive={setNeetoKbArticleState}
+            />
+          )}
           {children}
-          <EditorContent
-            className={contentWrapperClassName}
-            {...{ editor, ...otherProps }}
-          />
+          <div style={{ position: "relative" }}>
```
Comment (praveen-murali-ind) [inline src/components/Editor/index.jsx]: @SumitPanda0 This inline style is breaking the entire document editor layout.

Image

Image
